majager/gazebo_ros_control/pid_gains:
  Base_to_Link1: {p: 30000.0, i: 100.0, d: 900.0}
  Link1_to_Link2: {p: 24000.0, i: 100.0, d: 800.0}
  Link2_to_Link3: {p: 20000.0, i: 100.0, d: 700.0}
  Link3_to_Link4: {p: 18000.0, i: 100.0, d: 700.0}
  Link4_to_Link5: {p: 18000.0, i: 100.0, d: 700.0}
  Link5_to_Link6: {p: 18000.0, i: 100.0, d: 700.0}
  Link6_to_Base_Gripper: {p: 18000.0, i: 100.0, d: 700.0}
  Base_Gripper_to_Gripper_Right: {p: 1000.0, d: 50, i: 10}
  Base_Gripper_to_Gripper_Left: {p: 1000.0, d: 50, i: 10}
